[package]
name = "prime_factors"
version = "0.1.0"
authors = ["kiddspazz <travis@travish.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
